apartments_model = {
        "id" : "",
        "landlord_id": "",
        "apartment_name" : "",
        "country": "",
        "city": "",
        "zip_code": "",
        "street": "",
        "street_number": "",
        "building number": "",
        "apartment_number": "",
        "floor": "",
        "other_specification": "",
        "surface": "",
        "exposition": "",
        "year_of_construction": "",
        "shared_flat": "",
        "number_of_rooms": "",
        "average_ratings":""
        }
