landlords_model = {
        "id" : "",
        "first_name" : "",
        "last_name" : "",
        "date_of_birth": "",
        "country": "",
        "city": "",
        "zip_code": "",
        "street": "",
        "street_number": "",
        "building number": "",
        "apartment_number": "",
        "floor": "",
        "other_specification": "",
        "phone_number": "",
        "email": "",
        "average_ratings": ""}
